### ISSUE TITLE
Big guy, all your demo hardware, can you give me a list, I want to buy

### ISSUE THREAD

**Issue by yaobo-lab** [milewski/sensors-esp#1]
Big guy, all your demo hardware, can you give me a list, I want to buy？

thanks a lot！

**Comment by milewski** [comment]
Hey most of these components are very easy to find over electronics sites... is there one in specific that you don't know which is that you would like to buy? All of them were bought in Taobao (Aliexpress), some even came in kits with a bunch of random stuff in it...

**Comment by yaobo-lab** [comment]
> Hey most of these components are very easy to find over electronics sites... is there one in specific that you don't know which is that you would like to buy? All of them were bought in Taobao (Aliexpress), some even came in kits with a bunch of random stuff in it...

Can you give me the link to your purchase? I'm afraid I made a mistake. I want to learn from you

**Comment by milewski** [comment]
I have purchase most of the things from this shop: https://zejie.tmall.com/shop/view_shop.htm but Im not sure if you can open it outside china.

**Comment by yaobo-lab** [comment]
> I have purchase most of the things from this shop: https://zejie.tmall.com/shop/view_shop.htm but Im not sure if you can open it outside china.

thx a lot
